# Generated by Django 3.1.4 on 2021-03-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=20)),
            ],
        ),
    ]
