# Generated by Django 3.1.4 on 2021-03-09 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210309_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='timrStamp',
            new_name='timeStamp',
        ),
        migrations.AddField(
            model_name='post',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
