# Generated by Django 3.1.4 on 2021-03-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210309_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='comment',
            new_name='blog_comment',
        ),
    ]
