# Generated by Django 3.1.4 on 2021-03-09 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210309_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='blog_comment',
            new_name='comment',
        ),
    ]
