# Generated by Django 3.1.4 on 2021-03-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='timeStamp',
            field=models.DateTimeField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
